services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/url_shortener?schema=public
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - url-shortener-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - url-shortener-network

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - url-shortener-network

volumes:
  postgres-data:

networks:
  url-shortener-network:
    driver: bridge
